import "@/styles/reset.css";
import "@/styles/globals.css";

import { Header } from "@/components/header";
import { Tabs } from "@/components/tabs";
import { DataProvider } from "@/context/data-context";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <DataProvider>
          <Header />
          <Tabs />
          <main>{children}</main>
        </DataProvider>
      </body>
    </html>
  );
}
